# Generated by Django 5.0.3 on 2024-03-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessories', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MuscleAnatomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscleName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workoutType', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('instructions', models.TextField()),
                ('duration', models.IntegerField()),
                ('repetition', models.CharField(max_length=20)),
                ('restTime', models.CharField(max_length=20)),
                ('accessories', models.ManyToManyField(to='workouts.accessories')),
                ('target_muscles', models.ManyToManyField(to='workouts.muscleanatomy')),
                ('workoutType', models.ManyToManyField(to='workouts.workouttypes')),
            ],
        ),
    ]
