# Generated by Django 5.0.3 on 2024-03-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='accessories',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workouts',
            name='accessories',
            field=models.ManyToManyField(blank=True, null=True, to='workouts.accessories'),
        ),
    ]
