# Generated by Django 5.0.3 on 2024-03-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_alter_workouts_workouttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouts',
            name='workoutType',
            field=models.ManyToManyField(to='workouts.workouttypes'),
        ),
    ]
