# Generated by Django 5.0.3 on 2024-03-09 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_alter_workouts_workouttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workouts',
            old_name='target_muscles',
            new_name='targetMuscles',
        ),
    ]
