# Generated by Django 5.0.3 on 2024-03-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_rename_target_muscles_workouts_targetmuscles'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouts',
            name='level',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Master', 'Master')], default='', max_length=15),
        ),
    ]
